---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-postgres-secret
  namespace: keycloakx
spec:
  encryptedData:
    password: AgAf+dJVCKQAEza1YY9/koXTsgvZdSrqAYQ8HBZo0xlPgL+O/LIVz2hK+tRpH7sTzyFWfNGJJVFgaP5o2Aend/wYfK5cBzmDC+lFg5m+vjlBvz8NiMA9KWDFoZ9mPumK5PlGpfCG2cWViSwsHCk6o/sIS3k3CMe7M2GPbEY2mDQeR6VseTGkOYQHhMYKjFLYJRPSNh4jRqp6c2fXQidl1sQFn9ll5PMm9BBXjHOMzzmDiG6oVHGsJjsMQR0Q1yf2uMtKdhauQAG/Gb1v2bwsSCGPbGAIrxOrzV3Mhw76fTiSJL58lYhMd4v2QezUAKgAjACULXX5jViklhUietAaGaKnTDxgdgsyAt+CErQnnlQ8UMGqLlG6XjJvY1NLcm3aulJBLzDRZ+GxsaC3Sgaj3oILLAdf3O5iKyVfTCGsZVjzCeyj3mZwTGOC89Hr+GS+4CetCukM4VfWl3SKddkjVSscmcAYBD9qXJzxE7Xe8LqS6cSIt0t0MVQav17KCFmgcDyBPZSqm+cdo8GezmFouUw2BsP68GkL/6M2eZWmOpwym/fO5WCzaqAJ4rb+osUXyWiS9G2CJL3Kt3m0IQQB22gAnmRKpHqMDo/MSM1jKGrshgTR30UTttIXXUw6grnIl1xTaSXDaX0arAMgqVRCRvesRS0uMHJj9Z5OzWsyv9mHgAxSyywjjWCyeQJt4F8LR6h3kcg5kgbkIq+yHpXWddL45Zs3cFgi
  template:
    metadata:
      name: keycloak-postgres-secret
      namespace: keycloakx
