---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psql-client-secret
  namespace: cnpg
spec:
  encryptedData:
    uri: AgASyYt4pQmwtnyC4535ShQbU0UVfTiI51XTYo/IQwCH4HNcHqoa2dMu4QF/fW1veXONvdUXUIjbYReolVGObt2Fr4aadwXDr95Ka8ubNqFO9n3Z/K/r0emXvyxBvyP1yN/XSX/jxvoA82jeeo+nACv7G3MJJqvnqPmF6fL83JdyOLakLQTqubEJirmDlUPZsCzkJlRlxXsaP+GCAUise3Ba79q9f7QFSUJ100aKuYZDuJaxCvWUzRGNemt+ObA4g6UAHVoCg6QNsOxhrjYod7IAkeUU3FIIEL8Smwx+LNwTPbhueBHdjYRZ2b+gNDhhdioRTSz4KSWg3lxx9uYHlHFCNRCDpaSOIGe+cuP9yqm0yCPHegR2RkUXViqesaX5Uu48YXEwEivmJ3lVXUii691JiQc3t7IhixzxyXA07htecMT08F1jdoZ5wRo1cP7H5H1UaordipyBrthBvY2ChSVwUoxyUD32HTdamQ5mphPrtNi/YHfKQoFT0ifW+FMS10SvJMBAFmrOJDhxUu5SU5E/u1RTCkgxZa/m06V0rJGLKrQkKJlbD52bQnfUUKl3Th3ZzNjCuvxknvngqx4sAMmmiKMu2XTmy2rP9l/iW0H4fuX1IeiX+xhkbqYUTtjJlV7GhSvZxUSJb5vcPM1CusLoMX0K+cpLfgyK5xA/6ZBnVvkAF4tZz5y5k9LGCJUQUX2EvAaBFXxFFKRwD2Ow1Yl2RkvRjBosZw2m7bZIb4fopTEi8EreCe9eErTTpAnLcowAJyDTaCNFMh062MiX1WwYDNL8i3QiNlBYuHDTbeeEgl8mCuGdS4fmAz8OJyTICFLihTU3Ahw0THl5459TdV+lEUfkiUs+FW0b
  template:
    metadata:
      name: psql-client-secret
      namespace: cnpg
